apiVersion: v1
kind: Service
metadata:
  name: team-devices-frontend
  labels:
    app: team-devices
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: team-devices
    tier: frontend