apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: team-devices-frontend
  labels:
    app: team-devices

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: team-devices
        tier: frontend
    spec:
      containers:
      - name: team-devices-app
        
        image: gcr.io/devices-map/team-devices:0.1
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        
        ports:
        - name: http-server
          containerPort: 4001
        env:
          - name: PROJECT_ID
            value: devices-map